#pragma once

enum class Setting
{
    PID_G,
    PID_T_I,
    PID_T_D,
    PID_OUT_MIN,
    PID_OUT_MAX,

    MOTOR_SPEED_FILTER_ALPHA,
    MOTOR_FB_PWM_MIN,
    MOTOR_FB_PWM_MAX,
    MOTOR_PWM_MIN,
    MOTOR_PWM_STOP,
    MOTOR_PWM_MAX,
    MOTOR_PWM_DEADBAND_FWD,
    MOTOR_PWM_DEADBAND_BWD,
    MOTOR_PWD_GAIN_FWD,
    MOTOR_PWD_GAIN_BWD,
};